# Its used to mention the base image for the docker image which we are going to create. It should be the first line in the dockerfile. It can be any image from dockerhub or any custom image created by us.

FROM redhat/ubi9