# It is used to add metadata to the image in the form of key-value pairs.
# It can be used to add information about the image such as the author, version, description, etc. 
# It can also be used to add labels to the image which can be used to organize and categorize the images.
# It is not mandatory to use LABEL instruction in a Dockerfile but it is a good practice to use it to add metadata to the image.

FROM almalinux:9
LABEL COURSE="Docker for Developers" \
      AUTHOR="Omkareshwar Basare" \
      VERSION="1.0" \
      DESCRIPTION="This is a sample image for Docker for Developers course" \
      MAINTAINER="Omkareshwar Basare"