# The workdir instruction is used to set the working directory for the instructions which are present in the Dockerfile.
# It is used to set the working directory for the instructions which are present in the Dockerfile

FROM almalinux:9
RUN mkdir -p /app
WORKDIR /app
RUN echo "This is the working directory for the application" > /app/info.txt

