# used to copy the files from the host machine to the container. 
#It can be used to copy the files which are required by the application running inside the container. 
#It can also be used to copy the files which are required by the base image. 
#It is a good practice to use COPY instruction in a Dockerfile to copy the files which are required by the application running inside the container.

FROM nginx
COPY index.html /usr/share/nginx/html/index.html