# used to copy files from local to image but it has 2 extra features which are not present in COPY instruction.
# 1. It can be used to copy files from a URL(internet) to the image.
# 2. It can be used to copy files from a tar archive to the image.

