# To provide environment variables to the container at runtime, we can use the ENV instruction in the Dockerfile. 
#It is used to set environment variables in the container. 
#It can be used to set environment variables which are required by the application running inside the container. 
#It can also be used to set environment variables which are required by the base image. 
#It is a good practice to use ENV instruction in a Dockerfile to set environment variables which are required by the application running inside the container.

FROM almalinux:9
ENV APP_ENV=production